[package]
name = "bytes-kman"
version = "0.1.0"
edition = "2021"
description = "serialize and deserialize bytes, a simple way to comunicate to other computer or to save state!"
author = "konkitoman"
license = "GPL-3.0"
keywords = ["serialize", "deserialize", "bytes", "serialize and deserialize"]

[workspace]
members = ["derive"]

[features]
default = ["core", "std"]
core = []
std = []

[dependencies]
derive = {version = "0.1.0", path = "derive"}
