[package]
name = "bytes-kman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["derive"]

[features]
default = ["core", "std"]
core = []
std = []

[dependencies]
derive = {path = "derive"}
